/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Personal Website",
  "description": "Personal Website",
  "base": "/zoe-blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/zoe-blog/images/photo.jpg"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/zoe-blog/images/photo.jpg"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "href": "/zoe-blog/images/photo.jpg"
      }
    ],
    [
      "meta",
      {
        "http-quiv": "pragma",
        "cotent": "no-cache"
      }
    ],
    [
      "meta",
      {
        "http-quiv": "pragma",
        "cotent": "no-cache,must-revalidate"
      }
    ],
    [
      "meta",
      {
        "http-quiv": "expires",
        "cotent": "0"
      }
    ]
  ],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-40fbf5d0",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/handbook/ConditionalTypes.html",
      "relativePath": "handbook/ConditionalTypes.md",
      "key": "v-b5f4da10",
      "path": "/handbook/ConditionalTypes.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/handbook/Generics.html",
      "relativePath": "handbook/Generics.md",
      "key": "v-3f6cd958",
      "path": "/handbook/Generics.html"
    },
    {
      "title": "我的日志、笔记",
      "frontmatter": {},
      "regularPath": "/note/",
      "relativePath": "note/README.md",
      "key": "v-46c986f3",
      "path": "/note/",
      "headers": [
        {
          "level": 2,
          "title": "html",
          "slug": "html"
        },
        {
          "level": 2,
          "title": "js",
          "slug": "js"
        },
        {
          "level": 2,
          "title": "css",
          "slug": "css"
        }
      ]
    },
    {
      "title": "12-29",
      "frontmatter": {},
      "regularPath": "/note/one.html",
      "relativePath": "note/one.md",
      "key": "v-be7abc5c",
      "path": "/note/one.html"
    },
    {
      "title": "12-30",
      "frontmatter": {},
      "regularPath": "/note/two.html",
      "relativePath": "note/two.md",
      "key": "v-042a8286",
      "path": "/note/two.html"
    },
    {
      "title": "留言板",
      "frontmatter": {},
      "regularPath": "/others/",
      "relativePath": "others/README.md",
      "key": "v-42754f53",
      "path": "/others/",
      "headers": [
        {
          "level": 2,
          "title": "暂无",
          "slug": "暂无"
        }
      ]
    },
    {
      "title": "留言板一",
      "frontmatter": {},
      "regularPath": "/others/one.html",
      "relativePath": "others/one.md",
      "key": "v-ee777f20",
      "path": "/others/one.html",
      "headers": [
        {
          "level": 3,
          "title": "暂无最新",
          "slug": "暂无最新"
        }
      ]
    },
    {
      "title": "留言板二",
      "frontmatter": {},
      "regularPath": "/others/two.html",
      "relativePath": "others/two.md",
      "key": "v-c8bb5ab8",
      "path": "/others/two.html",
      "headers": [
        {
          "level": 3,
          "title": "暂无最新",
          "slug": "暂无最新"
        }
      ]
    },
    {
      "title": "我的相册",
      "frontmatter": {},
      "regularPath": "/photograph/",
      "relativePath": "photograph/README.md",
      "key": "v-7aa3739a",
      "path": "/photograph/",
      "headers": [
        {
          "level": 2,
          "title": "相册一",
          "slug": "相册一"
        },
        {
          "level": 2,
          "title": "相册二",
          "slug": "相册二"
        }
      ]
    },
    {
      "title": "相册一",
      "frontmatter": {},
      "regularPath": "/photograph/one.html",
      "relativePath": "photograph/one.md",
      "key": "v-6e0eb27e",
      "path": "/photograph/one.html"
    },
    {
      "title": "相册二",
      "frontmatter": {},
      "regularPath": "/photograph/two.html",
      "relativePath": "photograph/two.md",
      "key": "v-2cc3f09c",
      "path": "/photograph/two.html"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "subSidebar": "auto",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "我的博客",
        "items": [
          {
            "text": "我的笔记",
            "link": "/note/"
          },
          {
            "text": "我的相册",
            "link": "/photograph/"
          },
          {
            "text": "留言板",
            "link": "/others/"
          },
          {
            "text": "百度一下",
            "link": "https://baidu.com"
          }
        ]
      }
    ],
    "sidebar": [
      {
        "title": "欢迎学习",
        "path": "/",
        "collapsable": false,
        "children": [
          {
            "title": "学前必读",
            "path": "/"
          }
        ]
      },
      {
        "title": "基础学习",
        "path": "/handbook/ConditionalTypes",
        "collapsable": false,
        "children": [
          {
            "title": "条件类型",
            "path": "/handbook/ConditionalTypes"
          },
          {
            "title": "泛型",
            "path": "/handbook/Generics"
          }
        ]
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}